
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rio-sur-adventure-app # Asigna un nombre a la imagen
    container_name: rio-sur-adventure-container
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=3000
    
      # - GEMINI_API_KEY=your_api_key_here # Descomenta si necesitas variables de entorno
    
    # Descomenta las siguientes líneas para desarrollo local con hot-reloading
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    # command: npm run dev

networks:
  default:
    driver: bridge
